# Generated by Django 2.2.9 on 2020-08-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventosClassrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('quantidade_estudantes', models.IntegerField(verbose_name='Quantidade Professores')),
                ('turmas_criadas', models.IntegerField(verbose_name='Quantidade Interações')),
                ('posts_criados', models.IntegerField(verbose_name='Quantidade Pots Criados')),
            ],
        ),
        migrations.CreateModel(
            name='EventosDrive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('comentarios', models.IntegerField(verbose_name='Comentários')),
                ('visualizacoes', models.IntegerField(verbose_name='Visualizações')),
                ('criacao_arquivos', models.IntegerField(verbose_name='Arquivos criados')),
                ('compartilhamentos', models.IntegerField(verbose_name='Arquivos compartilhados')),
            ],
        ),
        migrations.CreateModel(
            name='InteracoesClassroomPorTipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Quando')),
                ('professores', models.IntegerField(verbose_name='Professores')),
                ('alunos', models.IntegerField(verbose_name='Alunos')),
                ('outros', models.IntegerField(verbose_name='Outros')),
            ],
        ),
        migrations.CreateModel(
            name='Logins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('logins', models.IntegerField(verbose_name='Quantidade')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('turmas_criadas', models.IntegerField(verbose_name='Turmas Criadas')),
                ('arquivos_criados', models.IntegerField(verbose_name='Arquivos Criados')),
                ('posts_criados', models.IntegerField(verbose_name='Pots Criados')),
                ('papel', models.CharField(choices=[('teacher', 'Professor'), ('student', 'Aluno')], max_length=50, verbose_name='Papel')),
                ('ultima_interacao', models.DateTimeField(verbose_name='Quando')),
            ],
        ),
        migrations.CreateModel(
            name='TotalTurmas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(verbose_name='Total')),
            ],
        ),
        migrations.CreateModel(
            name='TotalUsuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(verbose_name='Total')),
            ],
        ),
        migrations.CreateModel(
            name='UsoChromebooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('quantidade', models.IntegerField(verbose_name='quantidade')),
            ],
        ),
    ]
