# Generated by Django 2.2.9 on 2020-08-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashedu', '0002_auto_20200814_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='interacoesclassroomportipousuario',
            name='alunos_posts_criados',
            field=models.IntegerField(default=0, verbose_name='Número de posts criados por alunos'),
        ),
        migrations.AddField(
            model_name='interacoesclassroomportipousuario',
            name='professores_posts_criados',
            field=models.IntegerField(default=0, verbose_name='Número de posts criados por professores'),
        ),
        migrations.AddField(
            model_name='interacoesclassroomportipousuario',
            name='turmas_criadas',
            field=models.IntegerField(default=0, verbose_name='Número de turmas criadas'),
        ),
    ]
