# Generated by Django 2.2.9 on 2020-08-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashedu', '0003_auto_20200814_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioUsuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('uso_drive', models.IntegerField(verbose_name='Uso do Drive')),
                ('ultimo_acesso', models.CharField(max_length=100, verbose_name='Último acesso')),
                ('turmas_criadas', models.IntegerField(verbose_name='Turmas criadas')),
                ('posts_criados', models.IntegerField(verbose_name='Posts criados')),
                ('papel', models.CharField(choices=[('teacher', 'Professor'), ('student', 'Aluno')], max_length=50, verbose_name='Papel')),
                ('ultimo_acesso_classroom', models.CharField(max_length=100, verbose_name='Último acesso classroom')),
            ],
        ),
        migrations.DeleteModel(
            name='RelatorioUsuario',
        ),
    ]
