# Generated by Django 2.2.9 on 2020-08-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashedu', '0004_auto_20200814_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriousuarios',
            name='codigo_escola',
            field=models.IntegerField(default=0, verbose_name='Código Escola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relatoriousuarios',
            name='codigo_usuario',
            field=models.IntegerField(default=0, verbose_name='Código usuário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relatoriousuarios',
            name='inep',
            field=models.IntegerField(default=0, verbose_name='INEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relatoriousuarios',
            name='municipio',
            field=models.CharField(default='MUNICIPIO', max_length=200, verbose_name='Município'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relatoriousuarios',
            name='nome_escola',
            field=models.CharField(default='ESCOLA', max_length=254, verbose_name='Nome Escola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relatoriousuarios',
            name='regiao',
            field=models.CharField(default='REGIÃO', max_length=200, verbose_name='Região'),
            preserve_default=False,
        ),
    ]
