# Generated by Django 2.2.9 on 2020-08-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashedu', '0005_auto_20200814_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventosclassrom',
            name='posts_criados',
            field=models.BigIntegerField(verbose_name='Quantidade Pots Criados'),
        ),
        migrations.AlterField(
            model_name='eventosclassrom',
            name='quantidade_estudantes',
            field=models.BigIntegerField(verbose_name='Quantidade Professores'),
        ),
        migrations.AlterField(
            model_name='eventosclassrom',
            name='turmas_criadas',
            field=models.BigIntegerField(verbose_name='Quantidade Interações'),
        ),
        migrations.AlterField(
            model_name='eventosdrive',
            name='comentarios',
            field=models.BigIntegerField(verbose_name='Comentários'),
        ),
        migrations.AlterField(
            model_name='eventosdrive',
            name='compartilhamentos',
            field=models.BigIntegerField(verbose_name='Arquivos compartilhados'),
        ),
        migrations.AlterField(
            model_name='eventosdrive',
            name='criacao_arquivos',
            field=models.BigIntegerField(verbose_name='Arquivos criados'),
        ),
        migrations.AlterField(
            model_name='eventosdrive',
            name='visualizacoes',
            field=models.BigIntegerField(verbose_name='Visualizações'),
        ),
        migrations.AlterField(
            model_name='interacoesclassroomportipousuario',
            name='alunos',
            field=models.BigIntegerField(verbose_name='Alunos'),
        ),
        migrations.AlterField(
            model_name='interacoesclassroomportipousuario',
            name='alunos_posts_criados',
            field=models.BigIntegerField(default=0, verbose_name='Número de posts criados por alunos'),
        ),
        migrations.AlterField(
            model_name='interacoesclassroomportipousuario',
            name='outros',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Outros'),
        ),
        migrations.AlterField(
            model_name='interacoesclassroomportipousuario',
            name='professores',
            field=models.BigIntegerField(verbose_name='Professores'),
        ),
        migrations.AlterField(
            model_name='interacoesclassroomportipousuario',
            name='professores_posts_criados',
            field=models.BigIntegerField(default=0, verbose_name='Número de posts criados por professores'),
        ),
        migrations.AlterField(
            model_name='interacoesclassroomportipousuario',
            name='turmas_criadas',
            field=models.BigIntegerField(default=0, verbose_name='Número de turmas criadas'),
        ),
        migrations.AlterField(
            model_name='logins',
            name='logins',
            field=models.BigIntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='relatoriousuarios',
            name='codigo_escola',
            field=models.BigIntegerField(verbose_name='Código Escola'),
        ),
        migrations.AlterField(
            model_name='relatoriousuarios',
            name='codigo_usuario',
            field=models.BigIntegerField(verbose_name='Código usuário'),
        ),
        migrations.AlterField(
            model_name='relatoriousuarios',
            name='inep',
            field=models.BigIntegerField(verbose_name='INEP'),
        ),
        migrations.AlterField(
            model_name='relatoriousuarios',
            name='posts_criados',
            field=models.BigIntegerField(verbose_name='Posts criados'),
        ),
        migrations.AlterField(
            model_name='relatoriousuarios',
            name='turmas_criadas',
            field=models.BigIntegerField(verbose_name='Turmas criadas'),
        ),
        migrations.AlterField(
            model_name='relatoriousuarios',
            name='uso_drive',
            field=models.BigIntegerField(verbose_name='Uso do Drive'),
        ),
        migrations.AlterField(
            model_name='totalturmas',
            name='total',
            field=models.BigIntegerField(verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='totalusuarios',
            name='total',
            field=models.BigIntegerField(verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='usochromebooks',
            name='quantidade',
            field=models.BigIntegerField(verbose_name='quantidade'),
        ),
    ]
