# Generated by Django 2.2.9 on 2020-08-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashedu', '0006_auto_20200817_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriousuarios',
            name='papel',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Aluno', 'Aluno')], max_length=50, verbose_name='Papel'),
        ),
    ]
