# Generated by Django 2.2.9 on 2020-08-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IaIndicadorAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('inep', models.CharField(max_length=50, verbose_name='INEP')),
                ('regiao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Região')),
                ('municipio', models.CharField(max_length=50, verbose_name='Município')),
                ('cre', models.CharField(blank=True, max_length=100, null=True, verbose_name='CRE')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('acessaram', models.IntegerField(verbose_name='Acessaram')),
            ],
            options={
                'verbose_name': 'IA Aluno',
                'verbose_name_plural': 'IA Alunos',
            },
        ),
        migrations.CreateModel(
            name='IaIndicadorProfessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('inep', models.CharField(max_length=50, verbose_name='INEP')),
                ('regiao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Região')),
                ('municipio', models.CharField(max_length=50, verbose_name='Município')),
                ('cre', models.CharField(blank=True, max_length=100, null=True, verbose_name='CRE')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('acessaram', models.IntegerField(verbose_name='Acessaram')),
            ],
            options={
                'verbose_name': 'IA Aluno',
                'verbose_name_plural': 'IA Alunos',
            },
        ),
    ]
