# Generated by Django 2.2.9 on 2020-08-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_iaindicadoraluno_iaindicadorprofessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='iaindicadoraluno',
            name='logaram_hoje',
            field=models.IntegerField(default=0, verbose_name='Acessaram Hoje'),
        ),
        migrations.AddField(
            model_name='iaindicadorprofessor',
            name='logaram_hoje',
            field=models.IntegerField(default=0, verbose_name='Acessaram Hoje'),
        ),
    ]
