# Generated by Django 2.2.9 on 2020-08-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_auto_20200829_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iaindicadoraluno',
            name='logaram_hoje',
            field=models.IntegerField(verbose_name='Acessaram Hoje'),
        ),
        migrations.AlterField(
            model_name='iaindicadorprofessor',
            name='logaram_hoje',
            field=models.IntegerField(verbose_name='Acessaram Hoje'),
        ),
    ]
