# Generated by Django 2.2.9 on 2020-08-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_auto_20200829_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iaindicadoraluno',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='iaindicadorprofessor',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
