# Generated by Django 2.2.9 on 2020-08-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_auto_20200829_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('atividade_id', models.CharField(max_length=200, unique=True, verbose_name='ID')),
                ('due', models.DateTimeField(blank=True, null=True, verbose_name='Due')),
                ('state', models.CharField(max_length=50, verbose_name='Course State')),
                ('creator_id', models.CharField(max_length=100, verbose_name='Creator')),
                ('criado', models.CharField(max_length=100, verbose_name='Data criação')),
                ('atualizado', models.CharField(max_length=100, verbose_name='Data atualização')),
                ('turma_id', models.CharField(default='00000', max_length=200, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('professor_id', models.CharField(max_length=200, unique=True, verbose_name='Id')),
                ('matricula', models.CharField(max_length=50, null=True, verbose_name='Matricula')),
                ('cpf', models.CharField(max_length=50, null=True, verbose_name='Cpf')),
                ('ultimo_acesso', models.CharField(max_length=100, verbose_name='Ultimo acesso')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('turma_id', models.CharField(max_length=100, unique=True, verbose_name='id')),
                ('owner_id', models.CharField(max_length=100, verbose_name='Owner')),
                ('section', models.CharField(blank=True, max_length=255, null=True, verbose_name='Section')),
                ('owner_email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.AlterModelOptions(
            name='iaindicadorprofessor',
            options={'verbose_name': 'IA Professor', 'verbose_name_plural': 'IA Professores'},
        ),
    ]
