# Generated by Django 2.2.9 on 2020-08-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_auto_20200830_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadoresGeraisTodaOrganizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Quando')),
                ('professores', models.BigIntegerField(verbose_name='Professores')),
                ('alunos', models.BigIntegerField(verbose_name='Alunos')),
                ('turmas_criadas', models.BigIntegerField(default=0, verbose_name='Número de turmas criadas')),
                ('alunos_posts_criados', models.BigIntegerField(default=0, verbose_name='Número de posts criados por alunos')),
                ('professores_posts_criados', models.BigIntegerField(default=0, verbose_name='Número de posts criados por professores')),
                ('outros', models.BigIntegerField(blank=True, null=True, verbose_name='Outros')),
                ('total_meets', models.BigIntegerField(blank=True, null=True, verbose_name='Total de meets')),
                ('total_meets_web', models.BigIntegerField(blank=True, null=True, verbose_name='Total meets web')),
                ('total_meets_ios', models.BigIntegerField(blank=True, null=True, verbose_name='Total meets ios')),
                ('total_meets_android', models.BigIntegerField(blank=True, null=True, verbose_name='Total meets android')),
                ('total_minutos_meets', models.BigIntegerField(blank=True, null=True, verbose_name='Total em minutos')),
            ],
        ),
    ]
