# Generated by Django 2.2.9 on 2020-08-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_indicadoresgeraistodaorganizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='cre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CRE'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='inep',
            field=models.CharField(default=3123432, max_length=50, verbose_name='INEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividade',
            name='municipio',
            field=models.CharField(default='Sem município', max_length=50, verbose_name='Município'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividade',
            name='regiao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Região'),
        ),
        migrations.AddField(
            model_name='professor',
            name='cre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CRE'),
        ),
        migrations.AddField(
            model_name='professor',
            name='inep',
            field=models.CharField(default=2413242, max_length=50, verbose_name='INEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='municipio',
            field=models.CharField(default='Sem município', max_length=50, verbose_name='Município'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='regiao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Região'),
        ),
        migrations.AddField(
            model_name='turmas',
            name='cre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CRE'),
        ),
        migrations.AddField(
            model_name='turmas',
            name='inep',
            field=models.CharField(default=231233, max_length=50, verbose_name='INEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turmas',
            name='municipio',
            field=models.CharField(default='Sem município', max_length=50, verbose_name='Município'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turmas',
            name='regiao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Região'),
        ),
    ]
