# Generated by Django 2.2.9 on 2020-08-31 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_auto_20200831_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='cre',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='inep',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='regiao',
        ),
    ]
