# Generated by Django 2.2.9 on 2020-08-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0009_auto_20200831_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acessos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=255, verbose_name='Nome')),
                ('data', models.DateField(verbose_name='Data')),
                ('acesso', models.IntegerField(verbose_name='Acesso')),
            ],
        ),
    ]
