# Generated by Django 2.2.9 on 2020-08-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0011_acessos_papel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('aluno_id', models.CharField(max_length=200, unique=True, verbose_name='Id')),
                ('matricula', models.CharField(max_length=50, null=True, verbose_name='Matricula')),
                ('cpf', models.CharField(max_length=50, null=True, verbose_name='Cpf')),
                ('ultimo_acesso', models.CharField(max_length=100, verbose_name='Ultimo acesso')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
    ]
