# Generated by Django 2.2.9 on 2020-08-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0012_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorDeFinalDeSemana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('p_um_dia', models.IntegerField(verbose_name='Professor um dia')),
                ('p_dois_dias', models.IntegerField(verbose_name='Professor dois dias')),
                ('p_tres_dias', models.IntegerField(verbose_name='Professor tres dias')),
                ('p_quatro_dias', models.IntegerField(verbose_name='Professor quatro dias')),
                ('p_cinco_dias', models.IntegerField(verbose_name='Professor cinco dias')),
                ('a_um_dia', models.IntegerField(verbose_name='Aluno cinco dias')),
                ('a_dois_dias', models.IntegerField(verbose_name='Aluno cinco dias')),
                ('a_tres_dias', models.IntegerField(verbose_name='Aluno cinco dias')),
                ('a_quatro_dias', models.IntegerField(verbose_name='Aluno cinco dias')),
                ('a_cinco_dias', models.IntegerField(verbose_name='Aluno cinco dias')),
            ],
        ),
    ]
