# Generated by Django 2.2.9 on 2020-08-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0013_indicadordefinaldesemana'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadoresgeraistodaorganizacao',
            name='total_sete_dias',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Total 7 dias'),
        ),
        migrations.AddField(
            model_name='indicadoresgeraistodaorganizacao',
            name='total_trinta_dias',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Total 30 dias'),
        ),
    ]
