# Generated by Django 2.2.9 on 2020-09-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0014_auto_20200831_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ibge', models.BigIntegerField(verbose_name='Código Ibge')),
                ('nome', models.CharField(max_length=254, verbose_name='Nome')),
                ('latitude', models.CharField(max_length=50, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=50, verbose_name='Longitude')),
                ('capital', models.BooleanField(verbose_name='Capital')),
                ('codigo_uf', models.IntegerField(verbose_name='Código uf')),
            ],
        ),
        migrations.AddField(
            model_name='indicadordefinaldesemana',
            name='a_seis_dias',
            field=models.IntegerField(default=55, verbose_name='Aluno seis dias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicadordefinaldesemana',
            name='a_sete_dias',
            field=models.IntegerField(default=79, verbose_name='Aluno sete dias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicadordefinaldesemana',
            name='p_seis_dias',
            field=models.IntegerField(default=145, verbose_name='Professor seis dias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicadordefinaldesemana',
            name='p_sete_dias',
            field=models.IntegerField(default=19, verbose_name='Professor sete dias'),
            preserve_default=False,
        ),
    ]
