# Generated by Django 2.2.9 on 2020-09-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0014_auto_20200831_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadordefinaldesemana',
            name='a_seis_dias',
            field=models.IntegerField(default=55, verbose_name='Aluno seis dias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicadordefinaldesemana',
            name='a_sete_dias',
            field=models.IntegerField(default=79, verbose_name='Aluno sete dias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicadordefinaldesemana',
            name='p_seis_dias',
            field=models.IntegerField(default=145, verbose_name='Professor seis dias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicadordefinaldesemana',
            name='p_sete_dias',
            field=models.IntegerField(default=19, verbose_name='Professor sete dias'),
            preserve_default=False,
        ),
    ]
