# Generated by Django 2.2.9 on 2020-09-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0015_auto_20200901_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadordefinaldesemana',
            name='a_nenhum_dia',
            field=models.IntegerField(default=500000, verbose_name='Aluno nenhum dia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicadordefinaldesemana',
            name='p_nenhum_dia',
            field=models.IntegerField(default=20000, verbose_name='Professor nenhum dia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicadordefinaldesemana',
            name='a_seis_dias',
            field=models.IntegerField(verbose_name='Aluno seois dias'),
        ),
    ]
