# Generated by Django 2.2.9 on 2020-09-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0016_auto_20200901_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ibge', models.BigIntegerField(verbose_name='Código Ibge')),
                ('nome', models.CharField(max_length=254, verbose_name='Nome')),
                ('latitude', models.CharField(max_length=50, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=50, verbose_name='Longitude')),
                ('capital', models.BooleanField(verbose_name='Capital')),
                ('codigo_uf', models.IntegerField(verbose_name='Código uf')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='inep',
            field=models.IntegerField(default=12345324, verbose_name='Inep'),
            preserve_default=False,
        ),
    ]
