# Generated by Django 2.2.9 on 2020-09-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0017_auto_20200902_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='inep',
            field=models.IntegerField(default=1234, verbose_name='Inep'),
            preserve_default=False,
        ),
    ]
