# Generated by Django 2.2.9 on 2020-09-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0018_professor_inep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='inep',
            field=models.CharField(max_length=100, verbose_name='Inep'),
        ),
    ]
