# Generated by Django 2.2.9 on 2020-09-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0019_auto_20200902_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acessos',
            name='papel',
        ),
        migrations.AddField(
            model_name='acessos',
            name='inep',
            field=models.CharField(default=34432, max_length=100, verbose_name='Inep'),
            preserve_default=False,
        ),
    ]
