# Generated by Django 2.2.9 on 2020-09-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0020_auto_20200902_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='acessos',
            name='papel',
            field=models.CharField(default='Professor', max_length=50, verbose_name='Papel'),
            preserve_default=False,
        ),
    ]
