# Generated by Django 2.2.9 on 2020-09-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0021_acessos_papel'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadordefinaldesemana',
            name='cre',
            field=models.CharField(default='4', max_length=100, verbose_name='Cre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicadordefinaldesemana',
            name='escola',
            field=models.CharField(default='Escola semnome', max_length=100, verbose_name='Escola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicadordefinaldesemana',
            name='inep',
            field=models.CharField(default='3243', max_length=100, verbose_name='Inep'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicadordefinaldesemana',
            name='municipio',
            field=models.CharField(default='Qualuqer', max_length=100, verbose_name='Município'),
            preserve_default=False,
        ),
    ]
