# Generated by Django 2.2.9 on 2020-09-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0022_auto_20200902_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='inep',
            field=models.CharField(max_length=100, verbose_name='Inep'),
        ),
    ]
