# Generated by Django 2.2.9 on 2020-09-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0023_auto_20200902_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
