# Generated by Django 2.2.9 on 2020-09-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0024_auto_20200903_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispersaoAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('sete_dias', models.BigIntegerField(verbose_name='Sete dias')),
                ('quatorze_dias', models.BigIntegerField(verbose_name='QUatorze dias')),
                ('maior_quatorze_dias', models.BigIntegerField(verbose_name='Maior que 14 dias')),
                ('inep', models.CharField(max_length=50, verbose_name='INEP')),
                ('regiao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Região')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cre', models.CharField(blank=True, max_length=100, null=True, verbose_name='CRE')),
                ('municipio', models.CharField(max_length=50, verbose_name='Município')),
            ],
            options={
                'verbose_name': 'Dispersão Aluno',
                'verbose_name_plural': 'Dispersão Alunos',
            },
        ),
        migrations.CreateModel(
            name='DispersaoProfessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('sete_dias', models.BigIntegerField(verbose_name='Sete dias')),
                ('quatorze_dias', models.BigIntegerField(verbose_name='QUatorze dias')),
                ('maior_quatorze_dias', models.BigIntegerField(verbose_name='Maior que 14 dias')),
                ('inep', models.CharField(max_length=50, verbose_name='INEP')),
                ('regiao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Região')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cre', models.CharField(blank=True, max_length=100, null=True, verbose_name='CRE')),
                ('municipio', models.CharField(max_length=50, verbose_name='Município')),
            ],
            options={
                'verbose_name': 'Dispersão Professor',
                'verbose_name_plural': 'Dispersão Professores',
            },
        ),
    ]
