# Generated by Django 2.2.9 on 2020-09-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0025_dispersaoaluno_dispersaoprofessor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanalAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('total_atividades', models.BigIntegerField(verbose_name='Total de Atividades')),
                ('inep', models.CharField(max_length=50, verbose_name='INEP')),
                ('regiao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Região')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cre', models.CharField(blank=True, max_length=100, null=True, verbose_name='CRE')),
                ('municipio', models.CharField(max_length=50, verbose_name='Município')),
            ],
            options={
                'verbose_name': 'Relatório Semanal de Atividade',
                'verbose_name_plural': 'Relatório Semanal de Atividades',
            },
        ),
        migrations.AlterField(
            model_name='dispersaoprofessor',
            name='quatorze_dias',
            field=models.BigIntegerField(verbose_name='Quatorze dias'),
        ),
    ]
