# Generated by Django 2.2.9 on 2020-09-08 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0026_auto_20200908_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semanalatividade',
            name='data',
            field=models.DateField(default=datetime.datetime(2020, 9, 8, 11, 7, 38, 987613), verbose_name='Data'),
        ),
    ]
