# Generated by Django 2.2.9 on 2020-09-08 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0027_auto_20200908_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semanalatividade',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
    ]
