# Generated by Django 2.2.9 on 2020-09-08 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0028_auto_20200908_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispersaoaluno',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='dispersaoprofessor',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
    ]
