# Generated by Django 2.2.9 on 2020-09-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0029_auto_20200908_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='ultimo_acesso',
            field=models.DateField(verbose_name='Ultimo acesso'),
        ),
    ]
