# Generated by Django 2.2.9 on 2020-09-08 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0030_auto_20200908_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='ultimo_acesso',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ultimo acesso'),
        ),
    ]
