# Generated by Django 2.2.9 on 2020-09-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0032_auto_20200908_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
