# Generated by Django 2.2.9 on 2020-09-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0033_auto_20200908_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cpf'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='inep',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Inep'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Matricula'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='status',
            field=models.IntegerField(blank=True, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='ultimo_acesso',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Último Acesso'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='ultimo_acesso',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Último Acesso'),
        ),
    ]
