# Generated by Django 2.2.9 on 2020-09-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0034_auto_20200908_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadordefinaldesemana',
            name='iu_aluno',
            field=models.BigIntegerField(default=0, verbose_name='Iu aluno'),
        ),
        migrations.AddField(
            model_name='indicadordefinaldesemana',
            name='iu_professor',
            field=models.BigIntegerField(default=0, verbose_name='Iu professor'),
        ),
    ]
