# Generated by Django 2.2.9 on 2020-09-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0035_auto_20200909_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispersaoaluno',
            name='id_dispersao',
            field=models.BigIntegerField(default=0, verbose_name='Indicador de dispersão'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispersaoprofessor',
            name='id_dispersao',
            field=models.BigIntegerField(default=0, verbose_name='Indicador de dispersão'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iaindicadoraluno',
            name='ia',
            field=models.BigIntegerField(default=0, verbose_name='Indicador de adoção'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iaindicadorprofessor',
            name='ia',
            field=models.BigIntegerField(default=0, verbose_name='Indicador de adoção'),
            preserve_default=False,
        ),
    ]
