# Generated by Django 2.2.9 on 2020-09-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0036_auto_20200909_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cre',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Cre'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='escola',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Escola'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='municipio',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='regiao',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Região'),
        ),
        migrations.AddField(
            model_name='professor',
            name='cre',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Cre'),
        ),
        migrations.AddField(
            model_name='professor',
            name='escola',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Escola'),
        ),
        migrations.AddField(
            model_name='professor',
            name='municipio',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='professor',
            name='regiao',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Região'),
        ),
    ]
