# Generated by Django 2.2.9 on 2020-09-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0037_auto_20200909_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='idt',
            field=models.CharField(default='n', max_length=243, verbose_name='Longitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escola',
            name='latitude',
            field=models.CharField(default='n', max_length=243, verbose_name='Latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escola',
            name='longitude',
            field=models.CharField(default='n', max_length=243, verbose_name='Longitude'),
            preserve_default=False,
        ),
    ]
