# Generated by Django 2.2.9 on 2020-09-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0038_auto_20200910_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='ap',
            field=models.BigIntegerField(default=0, verbose_name='Atividades produzidas'),
        ),
        migrations.AddField(
            model_name='escola',
            name='ia_adocao',
            field=models.BigIntegerField(default=0, verbose_name='Indicador de adoção'),
        ),
        migrations.AddField(
            model_name='escola',
            name='id_dispersao',
            field=models.BigIntegerField(default=0, verbose_name='Indicador de dispersão'),
        ),
        migrations.AddField(
            model_name='escola',
            name='iu_uso',
            field=models.BigIntegerField(default=0, verbose_name='Indicador de uso'),
        ),
        migrations.AddField(
            model_name='escola',
            name='m_ap',
            field=models.BigIntegerField(default=0, verbose_name='Média de atividades produzidas'),
        ),
        migrations.AddField(
            model_name='escola',
            name='status',
            field=models.CharField(choices=[('Desenpenho ruim', 'Desenpenho ruim'), ('Desenpenho aceitável', 'Desenpenho aceitável'), ('Desenpenho ideal', 'Desenpenho ideal')], default='Desempenho ruim', max_length=50, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
