# Generated by Django 2.2.9 on 2020-09-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0039_auto_20200910_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escola',
            old_name='ap',
            new_name='ap_aluno',
        ),
        migrations.RenameField(
            model_name='escola',
            old_name='m_ap',
            new_name='map_aluno',
        ),
        migrations.RenameField(
            model_name='escola',
            old_name='status',
            new_name='status_aluno',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='ia_adocao',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='id_dispersao',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='iu_uso',
        ),
        migrations.AddField(
            model_name='escola',
            name='ap_professor',
            field=models.BigIntegerField(default=0, verbose_name='Atividades produzidas'),
        ),
        migrations.AddField(
            model_name='escola',
            name='ia_aluno',
            field=models.BigIntegerField(default=0, verbose_name='Indicador de adoção professor'),
        ),
        migrations.AddField(
            model_name='escola',
            name='ia_professor',
            field=models.BigIntegerField(default=0, verbose_name='Indicador de adoção professor'),
        ),
        migrations.AddField(
            model_name='escola',
            name='id_aluno',
            field=models.BigIntegerField(default=0, verbose_name='Indicador de dispersão professor'),
        ),
        migrations.AddField(
            model_name='escola',
            name='id_professor',
            field=models.BigIntegerField(default=0, verbose_name='Indicador de dispersão professor'),
        ),
        migrations.AddField(
            model_name='escola',
            name='iu_aluno',
            field=models.BigIntegerField(default=0, verbose_name='Indicador de uso professor'),
        ),
        migrations.AddField(
            model_name='escola',
            name='iu_professor',
            field=models.BigIntegerField(default=0, verbose_name='Indicador de uso professor'),
        ),
        migrations.AddField(
            model_name='escola',
            name='map_professor',
            field=models.BigIntegerField(default=0, verbose_name='Média de atividades produzidas'),
        ),
        migrations.AddField(
            model_name='escola',
            name='status_professor',
            field=models.CharField(choices=[('Desenpenho ruim', 'Desenpenho ruim'), ('Desenpenho aceitável', 'Desenpenho aceitável'), ('Desenpenho ideal', 'Desenpenho ideal')], default='n', max_length=50, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
