# Generated by Django 2.2.9 on 2020-09-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0040_auto_20200910_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipios',
            name='capital',
        ),
        migrations.RemoveField(
            model_name='municipios',
            name='codigo_ibge',
        ),
        migrations.RemoveField(
            model_name='municipios',
            name='codigo_uf',
        ),
        migrations.RemoveField(
            model_name='municipios',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='municipios',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='municipios',
            name='nome',
        ),
        migrations.AddField(
            model_name='escola',
            name='nome_cre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Cre'),
        ),
        migrations.AddField(
            model_name='municipios',
            name='ap_aluno',
            field=models.BigIntegerField(default=0, verbose_name='Atividades produzidas'),
        ),
        migrations.AddField(
            model_name='municipios',
            name='ap_professor',
            field=models.BigIntegerField(default=0, verbose_name='Atividades produzidas'),
        ),
        migrations.AddField(
            model_name='municipios',
            name='cre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CRE'),
        ),
        migrations.AddField(
            model_name='municipios',
            name='ia_aluno',
            field=models.BigIntegerField(default=0, verbose_name='Indicador de adoção professor'),
        ),
        migrations.AddField(
            model_name='municipios',
            name='ia_professor',
            field=models.BigIntegerField(default=0, verbose_name='Indicador de adoção professor'),
        ),
        migrations.AddField(
            model_name='municipios',
            name='id_aluno',
            field=models.BigIntegerField(default=0, verbose_name='Indicador de dispersão professor'),
        ),
        migrations.AddField(
            model_name='municipios',
            name='id_professor',
            field=models.BigIntegerField(default=0, verbose_name='Indicador de dispersão professor'),
        ),
        migrations.AddField(
            model_name='municipios',
            name='iu_aluno',
            field=models.BigIntegerField(default=0, verbose_name='Indicador de uso professor'),
        ),
        migrations.AddField(
            model_name='municipios',
            name='iu_professor',
            field=models.BigIntegerField(default=0, verbose_name='Indicador de uso professor'),
        ),
        migrations.AddField(
            model_name='municipios',
            name='map_aluno',
            field=models.BigIntegerField(default=0, verbose_name='Média de atividades produzidas'),
        ),
        migrations.AddField(
            model_name='municipios',
            name='map_professor',
            field=models.BigIntegerField(default=0, verbose_name='Média de atividades produzidas'),
        ),
        migrations.AddField(
            model_name='municipios',
            name='municipio',
            field=models.CharField(default='Sem nome', max_length=50, verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='municipios',
            name='nome_cre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Cre'),
        ),
        migrations.AddField(
            model_name='municipios',
            name='regiao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Região'),
        ),
        migrations.AddField(
            model_name='municipios',
            name='status_aluno',
            field=models.CharField(choices=[('Desenpenho ruim', 'Desenpenho ruim'), ('Desenpenho aceitável', 'Desenpenho aceitável'), ('Desenpenho ideal', 'Desenpenho ideal')], default='1', max_length=50, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipios',
            name='status_professor',
            field=models.CharField(choices=[('Desenpenho ruim', 'Desenpenho ruim'), ('Desenpenho aceitável', 'Desenpenho aceitável'), ('Desenpenho ideal', 'Desenpenho ideal')], default='2', max_length=50, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
