# Generated by Django 2.2.9 on 2020-09-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0041_auto_20200911_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoEnsalado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('aluno_id', models.CharField(max_length=200, unique=True, verbose_name='Id')),
                ('matricula', models.CharField(blank=True, max_length=50, null=True, verbose_name='Matricula')),
                ('cpf', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cpf')),
                ('ultimo_acesso', models.CharField(blank=True, max_length=255, null=True, verbose_name='Último Acesso')),
                ('inep', models.CharField(blank=True, max_length=100, null=True, verbose_name='Inep')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='Status')),
                ('municipio', models.CharField(blank=True, max_length=254, null=True, verbose_name='Município')),
                ('regiao', models.CharField(blank=True, max_length=254, null=True, verbose_name='Região')),
                ('cre', models.CharField(blank=True, max_length=254, null=True, verbose_name='Cre')),
                ('escola', models.CharField(blank=True, max_length=254, null=True, verbose_name='Escola')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
    ]
