# Generated by Django 2.2.9 on 2020-09-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0042_alunoensalado'),
    ]

    operations = [
        migrations.AddField(
            model_name='iaindicadorprofessor',
            name='acessaram_unicos',
            field=models.BigIntegerField(default=0, verbose_name='Professores logaram unicos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iaindicadorprofessor',
            name='total_unicos',
            field=models.BigIntegerField(default=0, verbose_name='Professores unicos'),
            preserve_default=False,
        ),
    ]
