# Generated by Django 2.2.9 on 2020-09-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0043_auto_20200918_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iaindicadorprofessor',
            name='acessaram_unicos',
        ),
        migrations.RemoveField(
            model_name='iaindicadorprofessor',
            name='total_unicos',
        ),
    ]
