# Generated by Django 2.2.9 on 2020-09-24 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0046_auto_20200918_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovoDispersaoAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('menor_sete', models.BigIntegerField(verbose_name='Sete dias')),
                ('maior_sete_menor_quatorze', models.BigIntegerField(verbose_name='Maior sete')),
                ('maior_quatorze_menor_trinta', models.BigIntegerField(verbose_name='Maior quatorzer')),
                ('maior_trinta_menor_sessenta', models.BigIntegerField(verbose_name='Maior trinta')),
                ('maior_sessenta', models.BigIntegerField(verbose_name='Maior sessenta')),
                ('inep', models.CharField(max_length=50, verbose_name='INEP')),
                ('regiao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Região')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cre', models.CharField(blank=True, max_length=100, null=True, verbose_name='CRE')),
                ('municipio', models.CharField(max_length=50, verbose_name='Município')),
                ('id_dispersao', models.BigIntegerField(verbose_name='Indicador de dispersão')),
            ],
            options={
                'verbose_name': 'Dispersão Aluno',
                'verbose_name_plural': 'Dispersão Alunos',
            },
        ),
    ]
