# Generated by Django 2.2.9 on 2020-09-24 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0047_novodispersaoaluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novodispersaoaluno',
            name='id_dispersao',
        ),
        migrations.RemoveField(
            model_name='novodispersaoaluno',
            name='nome',
        ),
    ]
