# Generated by Django 2.2.9 on 2020-09-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0049_novoiualuno'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovoIaAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('inep', models.CharField(max_length=100, verbose_name='Inep')),
                ('escola', models.CharField(max_length=100, verbose_name='Escola')),
                ('municipio', models.CharField(max_length=100, verbose_name='Município')),
                ('cre', models.CharField(max_length=100, verbose_name='Cre')),
                ('total_alunos', models.IntegerField(verbose_name='Aluno um dia')),
                ('total_logaram', models.IntegerField(verbose_name='Aluno dois dias')),
            ],
        ),
        migrations.AlterField(
            model_name='novoiualuno',
            name='a_dois_dias',
            field=models.IntegerField(verbose_name='Aluno dois dias'),
        ),
        migrations.AlterField(
            model_name='novoiualuno',
            name='a_quatro_dias',
            field=models.IntegerField(verbose_name='Aluno quatro dias'),
        ),
        migrations.AlterField(
            model_name='novoiualuno',
            name='a_seis_dias',
            field=models.IntegerField(verbose_name='Aluno seis dias'),
        ),
        migrations.AlterField(
            model_name='novoiualuno',
            name='a_tres_dias',
            field=models.IntegerField(verbose_name='Aluno tres dias'),
        ),
        migrations.AlterField(
            model_name='novoiualuno',
            name='a_um_dia',
            field=models.IntegerField(verbose_name='Aluno um dia'),
        ),
    ]
