# Generated by Django 2.2.9 on 2020-09-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0050_auto_20200925_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovoStatusAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inep', models.CharField(max_length=100, verbose_name='Inep')),
                ('escola', models.CharField(max_length=100, verbose_name='Escola')),
                ('municipio', models.CharField(max_length=100, verbose_name='Município')),
                ('cre', models.CharField(max_length=100, verbose_name='Cre')),
                ('total_alunos', models.IntegerField(verbose_name='Aluno um dia')),
                ('total_logaram', models.IntegerField(verbose_name='Aluno dois dias')),
            ],
        ),
    ]
