# Generated by Django 2.2.9 on 2020-09-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0051_novostatusaluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novostatusaluno',
            name='total_alunos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Aluno um dia'),
        ),
        migrations.AlterField(
            model_name='novostatusaluno',
            name='total_logaram',
            field=models.IntegerField(blank=True, null=True, verbose_name='Aluno dois dias'),
        ),
    ]
