# Generated by Django 2.2.9 on 2020-09-25 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0054_novodispersaoprofessor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novoiuprofessor',
            old_name='a_cinco_dias',
            new_name='p_cinco_dias',
        ),
        migrations.RenameField(
            model_name='novoiuprofessor',
            old_name='a_dois_dias',
            new_name='p_dois_dias',
        ),
        migrations.RenameField(
            model_name='novoiuprofessor',
            old_name='a_nenhum_dia',
            new_name='p_nenhum_dia',
        ),
        migrations.RenameField(
            model_name='novoiuprofessor',
            old_name='a_quatro_dias',
            new_name='p_quatro_dias',
        ),
        migrations.RenameField(
            model_name='novoiuprofessor',
            old_name='a_seis_dias',
            new_name='p_seis_dias',
        ),
        migrations.RenameField(
            model_name='novoiuprofessor',
            old_name='a_sete_dias',
            new_name='p_sete_dias',
        ),
        migrations.RenameField(
            model_name='novoiuprofessor',
            old_name='a_tres_dias',
            new_name='p_tres_dias',
        ),
        migrations.RenameField(
            model_name='novoiuprofessor',
            old_name='a_um_dia',
            new_name='p_um_dia',
        ),
    ]
