# Generated by Django 2.2.9 on 2020-09-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0055_auto_20200925_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovaAgrecacaoIaAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inep', models.CharField(max_length=50, verbose_name='INEP')),
                ('regiao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Região')),
                ('cre', models.CharField(blank=True, max_length=100, null=True, verbose_name='CRE')),
                ('municipio', models.CharField(max_length=50, verbose_name='Município')),
                ('total_ensalados', models.BigIntegerField(verbose_name='Total ensalados')),
                ('total_logados', models.BigIntegerField(verbose_name='Total alunos')),
            ],
        ),
    ]
