# Generated by Django 2.2.9 on 2020-09-28 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0056_novaagrecacaoiaaluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='novaagrecacaoiaaluno',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
    ]
