# Generated by Django 2.2.9 on 2020-09-28 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0057_novaagrecacaoiaaluno_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovoCadastroAtividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('data_publicacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('inep', models.CharField(max_length=50, verbose_name='INEP')),
                ('regiao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Região')),
                ('cre', models.CharField(blank=True, max_length=100, null=True, verbose_name='CRE')),
                ('municipio', models.CharField(max_length=50, verbose_name='Município')),
                ('componente_curricular', models.CharField(max_length=50, verbose_name='Componente curricular')),
                ('criador', models.CharField(max_length=50, verbose_name='Criador')),
                ('turma_id', models.CharField(max_length=50, verbose_name='Turma')),
                ('qtd_corrigida', models.BigIntegerField(verbose_name='Corrigidas')),
                ('qtd_nao_iniciada', models.BigIntegerField(verbose_name='Não iniciada')),
                ('qtd_atrasos', models.BigIntegerField(verbose_name='Atrasos')),
                ('qtd_vinculos', models.BigIntegerField(verbose_name='Vínculos')),
            ],
        ),
    ]
