# Generated by Django 2.2.9 on 2020-09-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0059_auto_20200928_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='novocadastroatividades',
            name='atividade_id',
            field=models.CharField(default='aasd', max_length=250, unique=True, verbose_name='Atividade Id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='novocadastroatividades',
            name='turma_id',
            field=models.CharField(max_length=250, verbose_name='Turma'),
        ),
    ]
