# Generated by Django 2.2.9 on 2020-09-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0060_auto_20200928_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='novocadastroatividades',
            name='qtd_iniciada',
            field=models.BigIntegerField(default=0, verbose_name='Iniciada'),
        ),
    ]
