# Generated by Django 2.2.9 on 2020-09-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0061_novocadastroatividades_qtd_iniciada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novocadastroatividades',
            name='atividade_id',
            field=models.CharField(max_length=250, verbose_name='Atividade Id'),
        ),
    ]
