# Generated by Django 2.2.9 on 2020-09-28 21:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0062_auto_20200928_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('codigo_meet', models.CharField(max_length=50, verbose_name='Código do Meet')),
                ('duracao', models.IntegerField(verbose_name='Duração do Meet')),
                ('media', models.IntegerField(verbose_name='Média de Permanência')),
                ('total_usuarios', models.IntegerField(verbose_name='Total de Usuários')),
                ('professores', models.IntegerField(verbose_name='Professores')),
                ('alunos', models.IntegerField(verbose_name='Alunos')),
                ('externos', models.IntegerField(verbose_name='Usuários Externos')),
                ('outros', models.IntegerField(verbose_name='Outros')),
                ('android', models.IntegerField(verbose_name='Usuários Android')),
                ('ios', models.IntegerField(verbose_name='Usuários iOS')),
                ('web', models.IntegerField(verbose_name='Usuários Web')),
                ('desconhecido', models.IntegerField(verbose_name='Dispositivos Desconhecidos')),
                ('cre', models.CharField(max_length=50, verbose_name='CRE')),
                ('municipio', models.CharField(max_length=50, verbose_name='Município')),
                ('inep', models.CharField(max_length=50, verbose_name='INEP')),
            ],
        ),
    ]
