# Generated by Django 2.2.9 on 2020-09-30 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0063_meet'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovaConsolidacaoGeralAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('inep', models.CharField(max_length=50, verbose_name='INEP')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('regiao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Região')),
                ('municipio', models.CharField(max_length=50, verbose_name='Município')),
                ('cre', models.CharField(blank=True, max_length=100, null=True, verbose_name='CRE')),
                ('nome_cre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Cre')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('sete_dias', models.BigIntegerField(verbose_name='Sete dias')),
                ('trinta_dias', models.BigIntegerField(verbose_name='Trinta dias')),
                ('sessenta_dias', models.BigIntegerField(verbose_name='Sessenta dias')),
                ('maior_sessenta_dias', models.BigIntegerField(verbose_name='Maior que 60 dias')),
                ('quatorze_dias', models.BigIntegerField(verbose_name='QUatorze dias')),
                ('maior_quatorze_dias', models.BigIntegerField(verbose_name='Maior que 14 dias')),
                ('a_um_dia', models.IntegerField(verbose_name='Aluno um dia')),
                ('a_dois_dias', models.IntegerField(verbose_name='Aluno dois dias')),
                ('a_tres_dias', models.IntegerField(verbose_name='Aluno tres dias')),
                ('a_quatro_dias', models.IntegerField(verbose_name='Aluno quatro dias')),
                ('a_cinco_dias', models.IntegerField(verbose_name='Aluno cinco dias')),
                ('a_seis_dias', models.IntegerField(verbose_name='Aluno seis dias')),
                ('a_sete_dias', models.IntegerField(verbose_name='Aluno sete dias')),
                ('a_nenhum_dia', models.IntegerField(verbose_name='Aluno nenhum dia')),
                ('total_alunos', models.IntegerField(verbose_name='Aluno um dia')),
                ('total_logaram', models.IntegerField(verbose_name='Aluno dois dias')),
            ],
        ),
    ]
