# Generated by Django 2.2.9 on 2020-09-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0064_novaconsolidacaogeralaluno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novaconsolidacaogeralaluno',
            old_name='sete_dias',
            new_name='menor_sete',
        ),
        migrations.RemoveField(
            model_name='novaconsolidacaogeralaluno',
            name='maior_quatorze_dias',
        ),
        migrations.RemoveField(
            model_name='novaconsolidacaogeralaluno',
            name='maior_sessenta_dias',
        ),
        migrations.RemoveField(
            model_name='novaconsolidacaogeralaluno',
            name='quatorze_dias',
        ),
        migrations.RemoveField(
            model_name='novaconsolidacaogeralaluno',
            name='sessenta_dias',
        ),
        migrations.RemoveField(
            model_name='novaconsolidacaogeralaluno',
            name='trinta_dias',
        ),
        migrations.AddField(
            model_name='novaconsolidacaogeralaluno',
            name='maior_quatorze_menor_trinta',
            field=models.BigIntegerField(default=0, verbose_name='Maior quatorzer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novaconsolidacaogeralaluno',
            name='maior_sessenta',
            field=models.BigIntegerField(default=0, verbose_name='Maior sessenta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novaconsolidacaogeralaluno',
            name='maior_sete_menor_quatorze',
            field=models.BigIntegerField(default=0, verbose_name='Maior sete'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novaconsolidacaogeralaluno',
            name='maior_trinta_menor_sessenta',
            field=models.BigIntegerField(default=0, verbose_name='Maior trinta'),
            preserve_default=False,
        ),
    ]
