# Generated by Django 2.2.9 on 2020-09-30 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0065_auto_20200930_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovaConsolidacaoGeralProfessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('inep', models.CharField(max_length=50, verbose_name='INEP')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('regiao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Região')),
                ('municipio', models.CharField(max_length=50, verbose_name='Município')),
                ('cre', models.CharField(blank=True, max_length=100, null=True, verbose_name='CRE')),
                ('nome_cre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Cre')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('menor_sete', models.BigIntegerField(verbose_name='Sete dias')),
                ('maior_sete_menor_quatorze', models.BigIntegerField(verbose_name='Maior sete')),
                ('maior_quatorze_menor_trinta', models.BigIntegerField(verbose_name='Maior quatorzer')),
                ('maior_trinta_menor_sessenta', models.BigIntegerField(verbose_name='Maior trinta')),
                ('maior_sessenta', models.BigIntegerField(verbose_name='Maior sessenta')),
                ('p_um_dia', models.IntegerField(verbose_name='Aluno um dia')),
                ('p_dois_dias', models.IntegerField(verbose_name='Aluno dois dias')),
                ('p_tres_dias', models.IntegerField(verbose_name='Aluno tres dias')),
                ('p_quatro_dias', models.IntegerField(verbose_name='Aluno quatro dias')),
                ('p_cinco_dias', models.IntegerField(verbose_name='Aluno cinco dias')),
                ('p_seis_dias', models.IntegerField(verbose_name='Aluno seis dias')),
                ('p_sete_dias', models.IntegerField(verbose_name='Aluno sete dias')),
                ('p_nenhum_dia', models.IntegerField(verbose_name='Aluno nenhum dia')),
                ('total_alunos', models.IntegerField(verbose_name='Aluno um dia')),
                ('total_logaram', models.IntegerField(verbose_name='Aluno dois dias')),
            ],
        ),
    ]
