# Generated by Django 2.2.9 on 2020-10-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0066_novaconsolidacaogeralprofessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='novaconsolidacaogeralaluno',
            name='cor',
            field=models.CharField(default='3', max_length=8, verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='novaconsolidacaogeralprofessor',
            name='cor',
            field=models.CharField(default='3', max_length=6, verbose_name='Cor'),
        ),
    ]
