# Generated by Django 2.2.9 on 2020-10-01 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0067_auto_20200930_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novaconsolidacaogeralaluno',
            name='cor',
            field=models.CharField(choices=[('Desenpenho ruim', 'Desenpenho ruim'), ('Desenpenho aceitável', 'Desenpenho aceitável'), ('Desenpenho ideal', 'Desenpenho ideal')], max_length=50, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='novaconsolidacaogeralprofessor',
            name='cor',
            field=models.CharField(choices=[('Desenpenho ruim', 'Desenpenho ruim'), ('Desenpenho aceitável', 'Desenpenho aceitável'), ('Desenpenho ideal', 'Desenpenho ideal')], default='3', max_length=50, verbose_name='Cor'),
        ),
    ]
