# Generated by Django 2.2.9 on 2020-10-01 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0068_auto_20200930_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novaconsolidacaogeralaluno',
            old_name='cor',
            new_name='status_aluno',
        ),
        migrations.RenameField(
            model_name='novaconsolidacaogeralprofessor',
            old_name='cor',
            new_name='status_professor',
        ),
    ]
