# Generated by Django 2.2.9 on 2020-10-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0070_auto_20201001_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltimoStatusAlunos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('inep', models.CharField(max_length=50, verbose_name='INEP')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('regiao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Região')),
                ('municipio', models.CharField(max_length=50, verbose_name='Município')),
                ('cre', models.CharField(blank=True, max_length=100, null=True, verbose_name='CRE')),
                ('nome_cre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Cre')),
                ('ia', models.BigIntegerField(default=0, verbose_name='Ia')),
                ('ie', models.BigIntegerField(default=0, verbose_name='Ie')),
                ('iu', models.BigIntegerField(default=0, verbose_name='Iu')),
                ('status_aluno', models.CharField(choices=[('Desenpenho ruim', 'Desenpenho ruim'), ('Desenpenho aceitável', 'Desenpenho aceitável'), ('Desenpenho ideal', 'Desenpenho ideal')], max_length=50, verbose_name='Cor')),
                ('menor_sete', models.BigIntegerField(verbose_name='Sete dias')),
                ('maior_sete_menor_quatorze', models.BigIntegerField(verbose_name='Maior sete')),
                ('maior_quatorze_menor_trinta', models.BigIntegerField(verbose_name='Maior quatorzer')),
                ('maior_trinta_menor_sessenta', models.BigIntegerField(verbose_name='Maior trinta')),
                ('maior_sessenta', models.BigIntegerField(verbose_name='Maior sessenta')),
                ('a_um_dia', models.IntegerField(verbose_name='Aluno um dia')),
                ('a_dois_dias', models.IntegerField(verbose_name='Aluno dois dias')),
                ('a_tres_dias', models.IntegerField(verbose_name='Aluno tres dias')),
                ('a_quatro_dias', models.IntegerField(verbose_name='Aluno quatro dias')),
                ('a_cinco_dias', models.IntegerField(verbose_name='Aluno cinco dias')),
                ('a_seis_dias', models.IntegerField(verbose_name='Aluno seis dias')),
                ('a_sete_dias', models.IntegerField(verbose_name='Aluno sete dias')),
                ('a_nenhum_dia', models.IntegerField(verbose_name='Aluno nenhum dia')),
                ('total_alunos', models.IntegerField(verbose_name='Aluno um dia')),
                ('total_logaram', models.IntegerField(verbose_name='Aluno dois dias')),
            ],
        ),
    ]
