# Generated by Django 2.2.9 on 2020-10-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0071_ultimostatusalunos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultimostatusalunos',
            name='a_cinco_dias',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Aluno cinco dias'),
        ),
        migrations.AlterField(
            model_name='ultimostatusalunos',
            name='a_dois_dias',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Aluno dois dias'),
        ),
        migrations.AlterField(
            model_name='ultimostatusalunos',
            name='a_nenhum_dia',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Aluno nenhum dia'),
        ),
        migrations.AlterField(
            model_name='ultimostatusalunos',
            name='a_quatro_dias',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Aluno quatro dias'),
        ),
        migrations.AlterField(
            model_name='ultimostatusalunos',
            name='a_seis_dias',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Aluno seis dias'),
        ),
        migrations.AlterField(
            model_name='ultimostatusalunos',
            name='a_sete_dias',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Aluno sete dias'),
        ),
        migrations.AlterField(
            model_name='ultimostatusalunos',
            name='a_tres_dias',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Aluno tres dias'),
        ),
        migrations.AlterField(
            model_name='ultimostatusalunos',
            name='a_um_dia',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Aluno um dia'),
        ),
        migrations.AlterField(
            model_name='ultimostatusalunos',
            name='ia',
            field=models.BigIntegerField(blank=True, default=0, null=True, unique=True, verbose_name='Ia'),
        ),
        migrations.AlterField(
            model_name='ultimostatusalunos',
            name='ie',
            field=models.BigIntegerField(blank=True, default=0, null=True, unique=True, verbose_name='Ie'),
        ),
        migrations.AlterField(
            model_name='ultimostatusalunos',
            name='inep',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='INEP'),
        ),
        migrations.AlterField(
            model_name='ultimostatusalunos',
            name='iu',
            field=models.BigIntegerField(blank=True, default=0, null=True, unique=True, verbose_name='Iu'),
        ),
        migrations.AlterField(
            model_name='ultimostatusalunos',
            name='maior_quatorze_menor_trinta',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Maior quatorzer'),
        ),
        migrations.AlterField(
            model_name='ultimostatusalunos',
            name='maior_sessenta',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Maior sessenta'),
        ),
        migrations.AlterField(
            model_name='ultimostatusalunos',
            name='maior_sete_menor_quatorze',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Maior sete'),
        ),
        migrations.AlterField(
            model_name='ultimostatusalunos',
            name='maior_trinta_menor_sessenta',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Maior trinta'),
        ),
        migrations.AlterField(
            model_name='ultimostatusalunos',
            name='menor_sete',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Sete dias'),
        ),
        migrations.AlterField(
            model_name='ultimostatusalunos',
            name='municipio',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='ultimostatusalunos',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='ultimostatusalunos',
            name='status_aluno',
            field=models.CharField(blank=True, choices=[('Desenpenho ruim', 'Desenpenho ruim'), ('Desenpenho aceitável', 'Desenpenho aceitável'), ('Desenpenho ideal', 'Desenpenho ideal')], max_length=50, null=True, unique=True, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='ultimostatusalunos',
            name='total_alunos',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Aluno um dia'),
        ),
        migrations.AlterField(
            model_name='ultimostatusalunos',
            name='total_logaram',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Aluno dois dias'),
        ),
    ]
