# Generated by Django 2.2.9 on 2020-10-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0073_auto_20201001_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltimoStatusProfessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('inep', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='INEP')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('regiao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Região')),
                ('municipio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Município')),
                ('cre', models.CharField(blank=True, max_length=100, null=True, verbose_name='CRE')),
                ('nome_cre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Cre')),
                ('ia', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Ia')),
                ('ie', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Ie')),
                ('iu', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Iu')),
                ('status_aluno', models.CharField(blank=True, choices=[('Desenpenho ruim', 'Desenpenho ruim'), ('Desenpenho aceitável', 'Desenpenho aceitável'), ('Desenpenho ideal', 'Desenpenho ideal')], max_length=50, null=True, verbose_name='Cor')),
                ('menor_sete', models.BigIntegerField(blank=True, null=True, verbose_name='Sete dias')),
                ('maior_sete_menor_quatorze', models.BigIntegerField(blank=True, null=True, verbose_name='Maior sete')),
                ('maior_quatorze_menor_trinta', models.BigIntegerField(blank=True, null=True, verbose_name='Maior quatorzer')),
                ('maior_trinta_menor_sessenta', models.BigIntegerField(blank=True, null=True, verbose_name='Maior trinta')),
                ('maior_sessenta', models.BigIntegerField(blank=True, null=True, verbose_name='Maior sessenta')),
                ('p_um_dia', models.IntegerField(blank=True, null=True, verbose_name='Aluno um dia')),
                ('p_dois_dias', models.IntegerField(blank=True, null=True, verbose_name='Aluno dois dias')),
                ('p_tres_dias', models.IntegerField(blank=True, null=True, verbose_name='Aluno tres dias')),
                ('p_quatro_dias', models.IntegerField(blank=True, null=True, verbose_name='Aluno quatro dias')),
                ('p_cinco_dias', models.IntegerField(blank=True, null=True, verbose_name='Aluno cinco dias')),
                ('p_seis_dias', models.IntegerField(blank=True, null=True, verbose_name='Aluno seis dias')),
                ('p_sete_dias', models.IntegerField(blank=True, null=True, verbose_name='Aluno sete dias')),
                ('p_nenhum_dia', models.IntegerField(blank=True, null=True, verbose_name='Aluno nenhum dia')),
                ('total_alunos', models.IntegerField(blank=True, null=True, verbose_name='Aluno um dia')),
                ('total_logaram', models.IntegerField(blank=True, null=True, verbose_name='Aluno dois dias')),
            ],
        ),
    ]
