# Generated by Django 2.2.9 on 2020-10-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0074_ultimostatusprofessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='novaconsolidacaogeralprofessor',
            name='ia',
            field=models.BigIntegerField(default=0, verbose_name='Ia'),
        ),
        migrations.AddField(
            model_name='novaconsolidacaogeralprofessor',
            name='ie',
            field=models.BigIntegerField(default=0, verbose_name='Ie'),
        ),
        migrations.AddField(
            model_name='novaconsolidacaogeralprofessor',
            name='iu',
            field=models.BigIntegerField(default=0, verbose_name='Iu'),
        ),
    ]
