# Generated by Django 2.2.9 on 2020-10-02 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0075_auto_20201002_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ultimostatusprofessor',
            old_name='status_aluno',
            new_name='status_professor',
        ),
    ]
