# Generated by Django 2.2.9 on 2020-10-07 01:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0076_auto_20201002_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncaoDocente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cre', models.CharField(blank=True, max_length=254, null=True, verbose_name='Cre')),
                ('municipio', models.CharField(blank=True, max_length=254, null=True, verbose_name='Município')),
                ('inep', models.CharField(blank=True, max_length=100, null=True, verbose_name='Inep')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('professor_id', models.CharField(max_length=200, unique=True, verbose_name='Id')),
                ('ultimo_acesso', models.DateField(default=django.utils.timezone.now, verbose_name='Último acesso')),
                ('primeiro_acesso', models.DateField(default=django.utils.timezone.now, verbose_name='Primeiro acesso')),
                ('acessos_ultima_semana', models.BigIntegerField(verbose_name='Acessos na última semana')),
                ('acessos_desde_inicio', models.BigIntegerField(verbose_name='Acessos desde inicio')),
                ('total_atividades', models.BigIntegerField(verbose_name='Total atividades')),
                ('atividades_ultima_semana', models.BigIntegerField(verbose_name='Atividades última semana')),
                ('meets_totais', models.BigIntegerField(verbose_name='Meets totais')),
                ('meets_ultima_semana', models.BigIntegerField(verbose_name='Meets última semana')),
            ],
        ),
    ]
