# Generated by Django 2.2.9 on 2020-10-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0077_funcaodocente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcaodocente',
            name='acessos_desde_inicio',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Acessos desde inicio'),
        ),
        migrations.AlterField(
            model_name='funcaodocente',
            name='acessos_ultima_semana',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Acessos na última semana'),
        ),
        migrations.AlterField(
            model_name='funcaodocente',
            name='atividades_ultima_semana',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Atividades última semana'),
        ),
        migrations.AlterField(
            model_name='funcaodocente',
            name='meets_totais',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Meets totais'),
        ),
        migrations.AlterField(
            model_name='funcaodocente',
            name='meets_ultima_semana',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Meets última semana'),
        ),
        migrations.AlterField(
            model_name='funcaodocente',
            name='total_atividades',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Total atividades'),
        ),
    ]
