# Generated by Django 2.2.9 on 2020-10-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0078_auto_20201006_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcaodocente',
            name='professor_id',
            field=models.CharField(max_length=200, verbose_name='Id'),
        ),
    ]
