# Generated by Django 2.2.9 on 2020-11-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0080_acessosalunos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessosalunos',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
