# Generated by Django 2.2.9 on 2020-11-09 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0081_auto_20201109_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessosalunos',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
    ]
