# Generated by Django 2.2.9 on 2020-11-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0084_ultimostatusalunos_lat_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultimostatusprofessor',
            name='lat_lon',
            field=models.CharField(blank=True, default='-00000000', max_length=255, null=True, verbose_name='Lat Lon'),
        ),
    ]
