# Generated by Django 2.2.9 on 2020-11-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0088_auto_20201116_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novoiuprofessor',
            name='escola',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Escola'),
        ),
    ]
