# Generated by Django 2.2.9 on 2020-12-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0090_auto_20201116_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultimostatusalunos',
            name='total_turmas',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total turmas'),
        ),
    ]
