# Generated by Django 2.2.9 on 2020-08-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('aluno_id', models.CharField(max_length=200, unique=True, verbose_name='Id')),
                ('matricula', models.CharField(max_length=50, null=True, verbose_name='Matricula')),
                ('cpf', models.CharField(max_length=50, null=True, verbose_name='Cpf')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('atividade_id', models.CharField(max_length=200, unique=True, verbose_name='ID')),
                ('due', models.DateTimeField(verbose_name='Due')),
                ('state', models.CharField(max_length=50, verbose_name='Course State')),
                ('creator_id', models.CharField(max_length=100, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('inep', models.CharField(max_length=50, verbose_name='INEP')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('regiao', models.CharField(max_length=200, verbose_name='Região')),
                ('municipio', models.CharField(max_length=50, verbose_name='Município')),
                ('cre', models.CharField(max_length=100, verbose_name='CRE')),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('professor_id', models.CharField(max_length=200, unique=True, verbose_name='Id')),
                ('matricula', models.CharField(max_length=50, null=True, verbose_name='Matricula')),
                ('cpf', models.CharField(max_length=50, null=True, verbose_name='Cpf')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('turma_id', models.CharField(max_length=100, unique=True, verbose_name='id')),
                ('owner_id', models.CharField(max_length=100, verbose_name='Owner')),
                ('section', models.CharField(blank=True, max_length=255, null=True, verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
    ]
