# Generated by Django 2.2.9 on 2020-08-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engajamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turmas',
            name='owner_email',
            field=models.EmailField(default='teste@teste.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atividade',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='turmas',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
    ]
