# Generated by Django 2.2.9 on 2020-08-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engajamento', '0002_auto_20200817_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escola',
            old_name='name',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='escola',
            name='cre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CRE'),
        ),
    ]
