# Generated by Django 2.2.9 on 2020-08-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engajamento', '0003_auto_20200817_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
    ]
