# Generated by Django 2.2.9 on 2020-08-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engajamento', '0004_auto_20200817_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='ultimo_acesso',
            field=models.CharField(default='2020-08-17', max_length=100, verbose_name='Ultimo acesso'),
            preserve_default=False,
        ),
    ]
