# Generated by Django 2.2.9 on 2020-08-17 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engajamento', '0005_professor_ultimo_acesso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='name',
            new_name='nome',
        ),
    ]
