# Generated by Django 2.2.9 on 2020-08-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engajamento', '0006_auto_20200817_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='atualizado',
            field=models.CharField(default='2020-08-17', max_length=100, verbose_name='Data atualização'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividade',
            name='criado',
            field=models.CharField(default='2020-08-17', max_length=100, verbose_name='Data criação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atividade',
            name='due',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Due'),
        ),
    ]
