# Generated by Django 2.2.9 on 2020-08-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engajamento', '0007_auto_20200817_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='turma_id',
            field=models.CharField(default='00000', max_length=200, verbose_name='ID'),
        ),
    ]
