# Generated by Django 2.2.9 on 2020-08-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engajamento', '0009_graficogeral'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraficoAuxiliar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.BigIntegerField(verbose_name='Total')),
                ('jalogaram_total', models.BigIntegerField(verbose_name='Total já logaram')),
                ('tipo_grafico', models.CharField(max_length=50, verbose_name='Tipo indicador')),
            ],
        ),
        migrations.CreateModel(
            name='GraficoEngajamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inep', models.CharField(max_length=50, verbose_name='Inep')),
                ('regiao', models.CharField(max_length=100, verbose_name='Região')),
                ('municipio', models.CharField(max_length=100, verbose_name='Município')),
                ('escola_nome', models.CharField(max_length=254, verbose_name='Escola Nome')),
                ('total_geral', models.BigIntegerField(verbose_name='Total geral')),
                ('jalogaram_geral', models.BigIntegerField(verbose_name='Togal geral já logaram')),
                ('total_alunos', models.BigIntegerField(verbose_name='Total alunos')),
                ('jalogaram_alunos', models.BigIntegerField(verbose_name='Total alunos já logaram')),
            ],
        ),
    ]
