# Generated by Django 2.2.9 on 2020-08-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engajamento', '0010_graficoauxiliar_graficoengajamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graficoauxiliar',
            name='jalogaram_total',
            field=models.BigIntegerField(default=0, verbose_name='Total já logaram'),
        ),
        migrations.AlterField(
            model_name='graficoauxiliar',
            name='tipo_grafico',
            field=models.CharField(default=0, max_length=50, verbose_name='Tipo indicador'),
        ),
        migrations.AlterField(
            model_name='graficoengajamento',
            name='jalogaram_alunos',
            field=models.BigIntegerField(default=0, verbose_name='Total alunos já logaram'),
        ),
        migrations.AlterField(
            model_name='graficoengajamento',
            name='jalogaram_geral',
            field=models.BigIntegerField(default=0, verbose_name='Togal geral já logaram'),
        ),
        migrations.AlterField(
            model_name='graficoengajamento',
            name='total_alunos',
            field=models.BigIntegerField(default=0, verbose_name='Total alunos'),
        ),
        migrations.AlterField(
            model_name='graficoengajamento',
            name='total_geral',
            field=models.BigIntegerField(default=0, verbose_name='Total geral'),
        ),
    ]
